# NumPy: arrays, operações vetorizadas e matrizes

Este notebook reúne exemplos curtos e executáveis sobre:
- criação de arrays e sequências numéricas;
- inspeção com `shape`, `dtype` e `size`;
- indexação e slicing;
- operações vetorizadas e funções úteis;
- matrizes e resolução de sistema linear.


In [1]:
import numpy as np

## 1. Criando arrays e sequências

In [10]:
notas = np.array([6.5, 7.0, 8.5, 9.0])
tempo = np.linspace(0, 10, 6)
pares = np.arange(0, 12, 2)

print("notas:", notas)
print("tempo:", tempo)
print("pares:", pares)

notas: [6.5 7.  8.5 9. ]
tempo: [ 0.  2.  4.  6.  8. 10.]
pares: [ 0  2  4  6  8 10]


## 2. Shape, dtype e size

In [28]:
medidas = np.array([[1.2, 1.5, 1.7],
                    [2.0, 2.2, 2.4]])

print("shape:", medidas.shape)
print("dtype:", medidas.dtype)
print("size:", medidas.size)

shape: (2, 3)
dtype: float64
size: 6


## 3. Indexação e slicing

In [38]:
M = np.array([[10, 11, 12], 
              [20, 21, 22], 
              [30, 31, 32]])


#print("elemento [0, 1]:", M[0, 1])
#print("terceira coluna:", M[:, 2])
#print("submatriz:\n", M[1:, :2])

submatriz = M[1:, 1:(M.shape[1])]
print(submatriz)

[[21 22]
 [31 32]]


## 4. Operações vetorizadas

In [39]:
temperaturas_c = np.array([18, 21, 25, 27])

temperaturas_f = temperaturas_c * 9 / 5 + 32

aumentadas = temperaturas_c + 2

print("temperaturas em Celsius:", temperaturas_c)
print("temperaturas em Fahrenheit:", temperaturas_f)
print("temperaturas + 2:", aumentadas)

temperaturas em Celsius: [18 21 25 27]
temperaturas em Fahrenheit: [64.4 69.8 77.  80.6]
temperaturas + 2: [20 23 27 29]


## 5. Funções úteis

In [8]:
dados = np.array([4, 6, 8, 10, 12])

print("soma:", np.sum(dados))
print("media:", np.mean(dados))
print("maximo:", np.max(dados))
print("minimo:", np.min(dados))

soma: 40
media: 8.0
maximo: 12
minimo: 4


## 6. Matrizes e álgebra linear

In [43]:
A = np.array([[3, 1],
              [1, 2]])
B = np.array([[2, 0],
              [1, 4]])
b = np.array([9, 8])

print("A @ B =\n", A @ B)
print("solucao de A x = b:", np.linalg.solve(A, b))

A @ B =
 [[7 4]
 [4 8]]
solucao de A x = b: [2. 3.]


## 7. Exemplo integrado

Vamos gerar um sinal, calcular estatísticas simples e reorganizar os dados em uma matriz.

In [67]:
x = np.linspace(0, 2 * np.pi, 8)
sinal = np.sin(x)
matriz_sinal = sinal.reshape(2, 4)

print("sinal:", np.round(sinal, 3))
print("media do sinal:", np.mean(sinal))
print("matriz 2x4:\n", np.round(matriz_sinal, 3))

sinal: [ 0.     0.782  0.975  0.434 -0.434 -0.975 -0.782 -0.   ]
media do sinal: -5.551115123125783e-17
matriz 2x4:
 [[ 0.     0.782  0.975  0.434]
 [-0.434 -0.975 -0.782 -0.   ]]
